#!/usr/bin/env bash
# volume.sh — probe state of the jetson_l4t Docker named volume.
#
# The volume holds the extracted Linux_for_Tegra/ tree (BSP + rootfs +
# generated flash images). prepare.sh writes it; flash.sh reads it.
# clean.sh trims it (build / rootfs / full).
#
# State is described by a single marker file at the volume root:
#   ${L4T_ROOT}/.prepared.yaml
#
# Generated by prepare.sh after each successful phase. Stores
# `jetpack_version: "6.2.2"` (canonical key) + `phases: [bsp, rootfs,
# binaries, user, images]` so the next prepare run can resume mid-
# pipeline or strict-mismatch-abort.

set -euo pipefail

# Caller must have already sourced errors.sh.
if ! declare -F emit_error >/dev/null; then
  printf 'volume.sh: emit_error not defined — source errors.sh first\n' >&2
  return 1
fi

# Mount point for the jetson_l4t Docker named volume. Distinct from
# the legacy ./data/nvidia_sdk bind mount used by the SDK Manager
# gui/cli stages so both flows coexist while PR-2 retires SDK Manager.
L4T_ROOT_DEFAULT="/srv/jetson_l4t"
L4T_ROOT="${L4T_ROOT:-${L4T_ROOT_DEFAULT}}"

# l4t_root_path <jetpack_version> <hw_targets>
# Echoes the canonical Linux_for_Tegra path inside the volume.
# Mirrors NVIDIA SDK Manager's layout so the existing data/ tree from
# pre-pivot installs still slots in.
l4t_root_path() {
  local jp="$1" hw="$2"
  printf '%s/JetPack_%s_Linux_%s/Linux_for_Tegra' "${L4T_ROOT}" "${jp}" "${hw}"
}

# volume_marker_path <jetpack_version> <hw_targets>
volume_marker_path() {
  printf '%s/.prepared.yaml' "$(l4t_root_path "$@")"
}

# volume_state <jetpack_version> <hw_targets>
# Echoes one of: empty | match | mismatch
volume_state() {
  local jp="$1" hw="$2"
  local marker
  marker="$(volume_marker_path "${jp}" "${hw}")"

  if [[ ! -f "${marker}" ]]; then
    if [[ -d "$(l4t_root_path "${jp}" "${hw}")" ]] && \
       [[ -n "$(ls -A "$(l4t_root_path "${jp}" "${hw}")" 2>/dev/null)" ]]; then
      printf 'mismatch'
      return 0
    fi
    printf 'empty'
    return 0
  fi

  local recorded recorded_hw
  recorded=$(yq -r '.jetpack_version' "${marker}" 2>/dev/null || true)
  recorded_hw=$(yq -r '.hw_targets' "${marker}" 2>/dev/null || true)
  # Both halves of the prepared-for identity must match: a JetPack bump
  # AND a board change are each a mismatch. hw_targets was recorded but
  # never compared before — path separation alone is not the guarantee.
  if [[ "${recorded}" == "${jp}" && "${recorded_hw}" == "${hw}" ]]; then
    printf 'match'
  else
    printf 'mismatch'
  fi
}

# volume_assert_match <jetpack_version> <hw_targets>
# Aborts with action message when state is `mismatch`.
volume_assert_match() {
  local jp="$1" hw="$2"
  local state
  state=$(volume_state "${jp}" "${hw}")
  case "${state}" in
    empty|match) return 0 ;;
    mismatch)
      emit_error \
        --category volume-mismatch \
        --detail "Volume jetson_l4t was prepared for a different JetPack/board than jetson.yaml asks for" \
        --action "Run \`./script/clean.sh l4t\` to wipe the volume" \
        --action "Re-run \`make run -- -t prepare\` to rebuild from scratch"
      return 1
      ;;
  esac
}

# volume_init_marker <jetpack_version> <hw_targets>
# Create the marker with an empty phase list if it does not exist yet.
# Called by prepare.sh BEFORE the first extraction so a crash mid-phase
# (before any volume_record_phase) leaves a matching marker behind — the
# next run then resumes (state=match, phases=[]) instead of seeing a
# non-empty dir with no marker and aborting as a forced-clean mismatch.
volume_init_marker() {
  local jp="$1" hw="$2"
  local marker
  marker="$(volume_marker_path "${jp}" "${hw}")"
  mkdir -p "$(dirname "${marker}")"

  if [[ ! -f "${marker}" ]]; then
    printf 'jetpack_version: "%s"\nhw_targets: "%s"\nphases: []\n' \
      "${jp}" "${hw}" >"${marker}"
  fi
}

# volume_record_phase <jetpack_version> <hw_targets> <phase>
# Append/update phase in the marker yaml.
volume_record_phase() {
  local jp="$1" hw="$2" phase="$3"
  local marker
  marker="$(volume_marker_path "${jp}" "${hw}")"
  volume_init_marker "${jp}" "${hw}"

  yq -i ".phases |= (. + [\"${phase}\"] | unique)" "${marker}"
}

# volume_phase_done <jetpack_version> <hw_targets> <phase>
#
# mikefarah yq does not implement jq's `index()`; using it falls through
# to "syntax error" + the resume path silently re-runs every step. Use
# `contains(["<phase>"])` which mikefarah does support — returns true
# when the array holds the phase, false otherwise, and `-e` flips false
# into a non-zero exit so the caller can branch on it.
volume_phase_done() {
  local jp="$1" hw="$2" phase="$3"
  local marker
  marker="$(volume_marker_path "${jp}" "${hw}")"
  [[ -f "${marker}" ]] || return 1
  yq -e ".phases | contains([\"${phase}\"])" "${marker}" >/dev/null 2>&1
}

# volume_drop_phase <jetpack_version> <hw_targets> <phase>
# Remove a phase from the marker so the next prepare re-runs that step.
# No-op when the marker or the phase is absent.
volume_drop_phase() {
  local jp="$1" hw="$2" phase="$3"
  local marker
  marker="$(volume_marker_path "${jp}" "${hw}")"
  [[ -f "${marker}" ]] || return 0
  yq -i "del(.phases[] | select(. == \"${phase}\"))" "${marker}"
}

# volume_record_storage_mode <jetpack_version> <hw_targets> <mode>
# Persist the storage MODE (internal|external) the images were built for.
# The marker tracks jetpack+board for the mismatch guard, but storage mode
# determines which flash images l4t_initrd_flash --no-flash produced, so
# flash.sh compares it to refuse a wrong-mode flash. clean.sh build/rootfs
# keep this field (same mode, just regenerate); only clean.sh l4t drops it
# with the whole marker.
volume_record_storage_mode() {
  local jp="$1" hw="$2" mode="$3"
  local marker
  marker="$(volume_marker_path "${jp}" "${hw}")"
  volume_init_marker "${jp}" "${hw}"
  yq -i ".storage_mode = \"${mode}\"" "${marker}"
}

# volume_storage_mode <jetpack_version> <hw_targets>
# Echoes the recorded storage mode, or empty when unrecorded (legacy marker
# written before storage_mode existed). Callers treat empty as "unknown —
# do not block" so pre-existing prepared volumes keep working.
volume_storage_mode() {
  local jp="$1" hw="$2"
  local marker
  marker="$(volume_marker_path "${jp}" "${hw}")"
  [[ -f "${marker}" ]] || return 0
  local m
  m=$(yq -r '.storage_mode // ""' "${marker}" 2>/dev/null || true)
  [[ "${m}" == "null" ]] && m=""
  printf '%s' "${m}"
}
