name: Main CI/CD

on:
  push:
    branches: [main, master]
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  call-docker-build:
    uses: ycpss91255-docker/base/.github/workflows/build-worker.yaml@v0.34.1
    with:
      image_name: jetson_sdk_manager
      build_runtime: false
      build_args: |
        BASE_IMAGE=ubuntu:22.04

  call-release:
    needs: call-docker-build
    if: startsWith(github.ref, 'refs/tags/')
    uses: ycpss91255-docker/base/.github/workflows/release-worker.yaml@v0.34.1
    with:
      archive_name_prefix: jetson_sdk_manager
